name: User Input Workflow

on:
  workflow_dispatch:
   inputs:
     quarantinetest:
     description: 'QurantineTests'     
     required: true
     default: ''
  push:
    branches: [ master, '[A-Z]+-[0-9]+**' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checking if conidition
      if: ${{ github.event.inputs.quarantinetest != '' }}
      run: |
        echo "Log level: ${{ github.event.inputs.quarantinetest }}"