name: User Input Workflow

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  inputs:
   logLevel:
     description: 'Log level'     
     required: true
     default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest