name: build-with-tests

on:
  workflow_dispatch:
    inputs:
      quarantineTest:
        description: 'QurantineTests'
        required: false
        default: ''
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build with Maven without quarantineTests
        if: ${{ github.event.inputs.quarantineTest == '' }}
        run: mvn -B package

      - name: Build with Maven with quarantineTests
        if: ${{ github.event.inputs.quarantineTest != '' }}
        run: |
          # Split the text into an array using commas as the delimiter
          IFS=',' read -ra words <<< "${{ github.event.inputs.quarantineTest }}"
          # Add "!" to the beginning of each word
          for i in "${!words[@]}"; do
            words[$i]="!${words[$i]}"
          done
          # Combine the words with commas
          quarantine_Tests=$(echo "${words[@]}" | tr ' ' ',')
          #Extract include from maven sure-fire plugin of pom file
          xmllint --xpath "//*[local-name()='project']/*[local-name()='build']/*[local-name()='plugins']/*[local-name()='plugin'][*[local-name()='artifactId']='maven-surefire-plugin']/*[local-name()='configuration']/*[local-name()='includes']/*[local-name()='include']/text()" >>includes
          
          #Initialize variable for combine includes
          finalIncludes=""
          
          #Read the file line by line
          while read line
          do
          # Split the line by commas and add it to the finalIncludes variable
          finalIncludes="${finalIncludes}${line},"
          done < includes
          
          #Remove last comma
          finalIncludes="${finalIncludes%,}"
          
          echo $quarantine_Tests,$finalIncludes          
          
          mvn -B -Dtest=$quarantine_Tests package
