name: ci-build

on:
  push:
      branches: [ master, '[A-Z]+-[0-9]+**' ]
  workflow_dispatch:
    inputs:
      quarantineTest:
        description: 'QurantineTests'
        required: true
        default: 'NA'
jobs:
  build:
    runs-on: tp2-self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build with Maven without quarantineTests
        if: ${{ github.event.inputs.quarantineTest == 'NA' }}
        run: mvn -B package

      - name: Build with Maven with quarantineTests
        if: ${{ github.event.inputs.quarantineTest != '' }}
        run: |
          # Split the text into an array using commas as the delimiter
          IFS=',' read -ra words <<< "${{ github.event.inputs.quarantineTest }}"
          # Add "!" to the beginning of each word
          for i in "${!words[@]}"; do
            words[$i]="!${words[$i]}"
          done
          # Combine the words with commas
          quarantine_Tests=$(echo "${words[@]}" | tr ' ' ',')
          
          mvn -B -Dtest=$quarantine_Tests package
