name: User Input Workflow

on:
  push:
   branches: [ master, '[A-Z]+-[0-9]+**' ]
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checking if condition
      run: mvn clean package