name: User Input Workflow

on:
  workflow_dispatch:
   inputs:
     logLevel:
       description: 'QurantineTests'     
       required: true
       default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checking if condition
      if: ${{ github.event.inputs.logLevel != '' }}
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"