name: User Input Workflow

on:
  push:
    branches: [ master, '[A-Z]+-[0-9]+**' ]
  workflow_dispatch:
   inputs:
     quarantinetest:
     description: 'QurantineTests'     
     required: true
     default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     if: ${{ github.event.inputs.quarantinetest != '' }}
    - run: |
        echo "Log level: ${{ github.event.inputs.quarantinetest }}"